apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blacklist-example
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: blacklist-example
    spec:
      serviceAccountName: blacklist-example
      containers:
        - name: blacklist-example
          image: tibbar/blacklist-example:latest
          command:
            - sh
            - -c
            - DEBUG=1 LOG_LEVEL=trace /usr/bin/blacklist-example
          imagePullPolicy: Always
          ports:
            # HTTP
            - containerPort: 8080