apiVersion: v1
kind: ServiceAccount
metadata:
  name: blacklist-example
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: blacklist-example-binding
subjects:
  - kind: ServiceAccount
    name: blacklist-example
    namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
