kind: Service
apiVersion: v1
metadata:
  name: blacklist-example
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: blacklist-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-blacklist
